apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments
spec:
  generators:
    - list:
        elements:
          - cluster: staging
            url: https://kubernetes.default.svc
          - cluster: prod
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{cluster}}-environment"
    spec:
      project: "{{cluster}}"
      source:
        repoURL: https://github.com/worldOneo/argo-test.git
        targetRevision: HEAD
        path: environments/{{cluster}}
      destination:
        server: "{{url}}"
        namespace: environment-{{cluster}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true