apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments
spec:
  generators:
    - list:
        elements:
          - environment: staging
            url: https://kubernetes.default.svc
          - environment: prod
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{environment}}-guestbook"
    spec:
      project: "{{environment}}"
      source:
        repoURL: https://github.com/worldOneo/argo-test.git
        targetRevision: HEAD
        path: environments/{{environment}}
      destination:
        server: "{{url}}"
        namespace: environment-{{environment}}
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true