apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
spec:
  destination:
    name: ''
    namespace: environment-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 3.7.4
    chart: mongodb-sharded
  project: prod