
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-prod
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: environment-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: environments/prod/mongodb
    repoURL: 'https://github.com/worldOneo/argo-test'
    targetRevision: HEAD
  project: prod
