apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-prod
  namespace: environment-prod
spec:
  destination:
    namespace: environment-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: bitnami/mongodb-sharded/
    repoURL: 'https://github.com/bitnami/charts/'
    targetRevision: 07c8e1f793bf2e664f1ab3db10822ccfd73e26fc
  project: prod
