apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-prod
spec:
  destination:
    name: ''
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: environments/prod/mongodb
    repoURL: 'https://github.com/worldOneo/argo-test'
    targetRevision: HEAD
  project: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true