apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  name: application-set-controller
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.1.0/manifests/install.yaml