apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: meta-ns
spec:
  destination:
    namespace: projects
    server: "https://kubernetes.default.svc"
  source:
    path: projects/
    repoURL: "https://github.com/worldOneo/argo-test.git"
    targetRevision: HEAD
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true