apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
spec:
  destination:
    name: ""
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: projects/
    repoURL: "https://github.com/worldOneo/argo-test.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - list:
        elements:
          - cluster: staging
            url: https://kubernetes.default.svc
          - cluster: prod
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{cluster}}-guestbook"
    spec:
      project: default
      source:
        repoURL: https://github.com/worldOneo/argo-test.git
        targetRevision: HEAD
        path: applications/{{cluster}}
      destination:
        server: "{{url}}"
        namespace: guestbook-{{cluster}}
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true