apiVersion: v2
name: mongodb-chart
version: 1.0.0
description: MongoDB chart for Kubernetes
appVersion: 1.0.0
dependencies:
  - name: mongodb-sharded
    version: 3.7.4
    repository: 'https://charts.bitnami.com/bitnami'