apiVersion: v2
type: application
name: mongodb-sharded-subchart
version: 1.0.0
description: MongoDB chart for Kubernetes
appVersion: 1.0.0
dependencies:
  - name: mongodb-sharded
    version: 3.7.4
    repository: 'https://charts.bitnami.com/bitnami'